FROM registry.aliyuncs.com/dracupid/ubuntu

ENV TESSDATA_PREFIX /usr/share/tesseract-ocr

ADD opencv-3.1.0_3.tar.gz /root/
COPY libso/* /usr/lib

# ADD 3.1.0.tar.gz /tmp/
# COPY ippicv_linux_20151201.tgz /tmp/opencv-3.1.0/3rdparty/ippicv/downloads/linux-808b791a6eac9ed78d32a7666804320e/
# RUN apt-get update \
#     && apt-get install -y tesseract-ocr \
#     && rm -rf /var/lib/apt/lists/*
# RUN apt-get clean
RUN apt-get update

RUN apt-get install -y build-essential cmake
RUN apt-get install -y cmake

# COPY cpp /root/
# RUN apt-get install -y git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libjpeg-dev libpng16-dev

# RUN apt-get install --no-install-recommends -y tesseract-ocr tesseract-ocr-chi-sim
# RUN apt-get install --no-install-recommends -y imagemagick

# RUN curl -OL https://github.com/Itseez/opencv/archive/3.1.0.tar.gz
#http://docs.opencv.org/3.1.0/d7/d9f/tutorial_linux_install.html
